### PR TITLE
Quote properly all CSP keywords.

### PR DESCRIPTION
**Pull request by nicdumz**
none, strict-dynamic, and unsafe-hashed-attributes should be quoted, per
https://w3c.github.io/webappsec-csp/#grammardef-keyword-source

Cheers!

### CODE REVIEW

**Comment by nicdumz** [comment]
Ping? ;-)

**Comment by nicdumz** [comment]
Actually, @jasonmit , I see that you're not with Yahoo anymore.

Could you pretty please loop in for me a former colleague that would be able to merge this request? I guess that anyone in https://github.com/orgs/yahoo/people can, or can they?

**Comment by adon-at-work** [comment]
pinging @ericf

**Comment by jlecomte** [comment]
This looks pretty harmless to me 👍 @adon-at-work, are you cool with this?

**Comment by adon-at-work** [comment]
👍

**Pull request merged**
